name: Generate Contributions SVG

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate contributions svg
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: fiona-cai
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Your palette (dark -> light)
          config_display: large
          config_timezone: America/Toronto
          config_output: svg
          config_padding: 0, 8
          config_order: isocalendar

          # Custom colors
          config_theme: none
          config_twemoji: yes
          config_gemoji: yes
          config_isocalendar: yes
          config_isocalendar_colors: "ABCCA3,E9B8C1,C0D9BA,EFCAD1"
